<?php
$title = 'Add Artist';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('artist', array('action' => 'add', 'id' => $this->id)));
?>
<h1><?php echo $this->escapeHtml($title) ?></h1>
<?php
echo $this->form()->openTag($form);
echo $this->formRow($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('submit'));
echo $this->form()->closeTag($form);
?>