<?php
$title = 'Delete Artist';
$this->headTitle($title);
$url = $this->url('artist', array('action' => 'delete', 'id'=>$this->id));
?>
<h1><?php echo $this->escapeHtml($title) ?></h1>
Etes-vous sûr de vouloir supprimer l'Artiste <?php $this->escapeHtml($artist->name) ?>" ?
<form action="<?php echo $url ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo $artist->id ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="Not" />
    </div>
</form>
